<?php

/**
 * @file
 * Paragraphy predefined bundles.
 */

/**
 * Implements hook_menu().
 */
function paragraphy_menu() {
  $items['admin/structure/paragraphs/paragraphy'] = array(
    'title' => 'Paragraphy',
    'type' => MENU_LOCAL_TASK,
    'page callback' => 'drupal_get_form',
    'page arguments' => array('paragraphy_settings_form'),
    'access arguments' => array('administer paragraphs bundles')
  );

  return $items;
}

/**
 * Settings form for module.
 *
 * @return array
 */
function paragraphy_settings_form() {
  // List of paragraphy types with data.
  $paragraphy_list = array(
    'paragraphy_wysiwyg' => array(
      'title' => 'Paragraphy WYSIWYG',
      'description' => t('Text field with WYSIWYG editor.'),
      // Boilerplate for time.
      'image' => 'https://raw.githubusercontent.com/Niklan/Glisseo/master/STARTER/screenshot.png',
    ),
  );

  $form['description'] = array(
    '#type' => 'markup',
    '#markup' => format_string(
      '<p>!text</p>',
      array(
        '!text' => t('On this page you can enable new paragraphs types just click for checkbox and save it. But when you uncheck this, bundle, with all this field will be removed.')
      )
    ),
  );

  foreach ($paragraphy_list as $name => $info) {
    $form[$name] = array(
      '#type' => 'markup',
      '#markup' => format_string(
        '<div class="@paragraphy_wrapper"><img src="@image_src" alt=""><div class="@wrapper_class"><h2 class="@title_class">@title</h2><p>@description</p></div></div>',
        array(
          '@paragraphy_wrapper' => 'paragraphy-item',
          '@image_src' =>  $info['image'],
          '@wrapper_class' => 'paragraphy-info',
          '@title_class' => 'title',
          '@title' => $info['title'],
          '@description' => $info['description'],
        )
      ),
    );
  }

  $form['#attached']['css'] = array(
    drupal_get_path('module', 'paragraphy') . '/styles/css/paragraphy_admin.css',
  );


  return $form;
}
